"""add_primary_color_to_tenants

Revision ID: cfb1e47fdad6
Revises: 6ceba707ab17
Create Date: 2026-03-13 16:03:27.765741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfb1e47fdad6'
down_revision: Union[str, Sequence[str], None] = '6ceba707ab17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('primary_color', sa.String(length=7), nullable=False, server_default='#E85D04'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'primary_color')
    # ### end Alembic commands ###
